# Generated by Django 5.2.4 on 2025-08-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_remove_product_features_productfeature_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('sales person', 'Salesperson')], default='customer', max_length=12),
        ),
    ]
