# Generated by Django 5.2.4 on 2025-08-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='product_count',
            field=models.PositiveIntegerField(default=0, max_length=2),
        ),
    ]
